### ISSUE TITLE
Modify CCS cost calculations to rely on power plant data within the EPS 

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#140] opened 2021-01-26 14:23 UTC
Our current approach for calculating the cost of CCS relies on calculations of cost per ton done outside Vensim in our input data. We then feed in capital cost in USD/ton CO2 removal, O&M costs, and energy penalty costs. The issue is that this blanket approach requires making some simple assumptions across all power plant types and years, which are not uniform across technologies. For example, to calculate the $/ton, we have to assume a power plant capacity factor, and emissions removal factor, and a heat rate.

Many of these factors vary widely across the power plant types in the model. For example, we have been exploring adding CCS to gas peakers to cover the last 5-10% of emissions, but these plants only run ~10% of the time, compared to an assumption of 85% in the data for CCS, which assumes coal plants running at baseload. This means the costs are roughly 1/8 what they should be. 

For the power sector, where there is large variation in utilization rates and efficiencies, we should consider moving to an approach of calculating costs based on $/kW, removal rates (which we can apply to the emissions rate for each plant type), and energy penalty percentages or absolute values, which we can apply to the heat rates in the EPS. This way, each power plant type would have its own, correct, calculation of of CCS costs and the model could easily calculate this dynamically for new regions with custom data. For industry, we may be able to stick with the current approach because industry energy utilization factors are likely to be pretty consistent across years and industry types (i.e. we expect industry to run near 100% capacity).

**Comment by jrissman** [comment] 2021-01-26 20:50
This is a good idea.

We currently have three types of CCS costs: capital costs, O&M costs, and fuel use to power the CCS equipment itself.  (Fuel costs are actually calculated downstream of fuel usage, so we need to get fuel use right here, and then fuel costs will be calculated elsewhere, correctly.)

It is easier to think of what needs to be done if we consider each of the these three things separately.

### Capital Cost
I see your data source in `ccs/CC` provides overnight capital costs in $/kW.  I had originally not used this unit because I believed that you could attach more or less CCS equipment to any given plant, and it doesn't necessarily correlate exactly with plant size.  It would just mean the plant has a higher or lower percentage of its CO2 captured.  I think CCS systems sometimes capture higher or lower percentages of the CO2 in the exhaust stream, so it seemed prudent to allow the EPS to be flexible in this way.  However, if in practice, a plant of a given size always receives CCS equipment of a given size, in every country, I could use $/kW unit for the input data.

It is not necessary to use a $/kW unit simply to fix the issue with varying power plant capacity factors.  Capital cost data are currently taken in $ per ton of CO2 captured per year.  This was intended to be a measure of the capacity of the CCS equipment.  You point out that if the equipment is attached to a power plant that only runs for one eighth of the year, the equipment only captures one eighth as much CO2 as it could, if that same equipment had been attached to a plant that ran full-time.  This means that "per ton CO2 captured per year" is in fact not a good measure of the CCS equipment's capacity.  It should be something like, "per ton of CO2 that would be captured per year if the equipment were used 100% of the year" to standardize it.  This can be done inside Vensim by dividing the capital cost per ton CO2 sequestered (if the CCS equipment were to run at 100% of the time) by the attached power plant's capacity factor, which would control for varying plant usage rates by plant type, and would dynamically adjust itself if the plants are dispatched more or less frequently within the model in future years.

So if all you need is the adjustment for varying power plant capacity factors, we could go with the latter approach of simply dividing the existing values by power plant capacity factors.  (I'd update the "About" text and possibly the name of the input variable to make is extremely clear what that variable is looking for, so users don't accidentally put already-normalized data in there.)  I am hesitant to switch to the $/kW unit for input data because I'm not sure if some world regions might attach smaller or larger CCS systems to a plant of a given size than the U.S. does, and switching to the $/kW unit removes the flexibility the EPS currently possesses that allows it to correctly handle this situation.

### Fuel Use
Fuel Use is currently taken in $ per ton of CO2 sequestered.  For the most part, I think this is fine, because the the CCS equipment isn't using fuel when it's not running, so it is correct that CCS equipment attached to a peaker plant uses less fuel than that same equipment would if it were attached to a plant that ran 100% of the time.

You bring up the issue of varying power plant heat rates - some plants use more fuel to generate electricity than other plants.  But the thing is, I think CCS equipment's energy use is not predominantly in the form of electricity.  I am under the impression that most of the energy demand is for heat, to regenerate the sorbent chemical (primarily hydroxide-based sorbents today).  Even a plant with a poor heat rate might generate the same amount of heat from a given quantity of coal or gas as a plant with a stellar heat rate.  So switching over to relying on heat rates entirely would over-estimate fuel usage, because a lot of the fuel doesn't have to be turned into electricity before being used by the CCS equipment.

But I suppose the CCS equipment must use _some_ electricity, for instance, for compression of the CO2, and other miscellaneous things.

If you need greater precision here, I think the way to do this is to take in separate input data on the amount of electricity and the amount of heat demanded by the CCS equipment, both per ton CO2 sequestered.  I can then add a heat rate adjustment to the electricity demand within Vensim, but I would not add any heat rate adjustment to the heat demand.

### O&M Costs

O&M cost data are currently taken in $ per ton of CO2 captured.  This would be fine if the O&M costs were essentially all variable O&M.  However, in the real world, O&M usually has fixed and variable components.  If you think CCS equipment has non-trivial fixed O&M costs, we will need to break this calculation apart into fixed O&M and variable O&M calculations.  Fixed O&M would be calculated similarly to capital cost (e.g. with a capacity factor adjustment), while variable O&M would be calculated as it is today (straight $/CO2 sequestered).

What do you think?

**Comment by jrissman** [comment] 2022-07-22 18:27
We completed the adjustment of CCS capacity required based on power plant capacity factors when resolving issue #211.

We don't need to make adjustments based on plant heat rate.  The CCS equipment is based on amount of fuel burned, not electricity generated, and the CCS solvent is regenerated with heat, not with electricity, so the efficiency of making electricity doesn't matter.

We still base O&M costs on amount of CO2 captured, not on quantity of CCS equipment installed.  It would be better to base O&M at least partially on quantity of equipment installed, though this might not be a large expense, relatively speaking.  This O&M piece is the last item to do in this GitHub issue before closing it.

**Comment by mkmahajan** [comment] 2023-09-12 17:48
This issue is no longer relevant now that we've redone the electricity sector CCS calculations.

**Closed by mkmahajan** 2023-09-12 17:48 UTC
Labels: low priority, 3.5
