### ISSUE TITLE
Subscript covid recession by fuel type

### ISSUE THREAD

**Issue by oashmoore** [EnergyInnovation/eps-us#177] opened 2021-07-21 16:53 UTC
In state models, we're running into calibration issues created by the covid recession due to inconsistant changes in fuel consumption within sectors. The most critical example - we're overestimating the drop in electricity demand. Also may be issues in the transportation sector (jet fuel consumption dropped far more than gas/diesel consumption). If EoSEUwGDPiR was subscript by fuel and sector it would fix this!

**Comment by jrissman** [comment] 2021-07-21 19:23
The COVID recession lever was added in early 2020 as a stopgap way to adjust the input data (which did not account for the pandemic) to reflect the pandemic effects.  But AEO 2021 (released in January 2021) included the pandemic's effects in its energy demand and other data, so we stopped using the COVID lever with the EPS 3.2.0 U.S. release.  This lever was never intended to be used long-term.

U.S. state models that are still in development or being updated as of July 2021 should be based on the AEO 2021 (and other data sources updated since the pandemic), so they shouldn't be using the COVID lever, just like the U.S. national model.  At least, that's my understanding.

Have you found the updated (AEO 2021) input data to be inaccurate?  What data are you comparing it to, in order to determine that it is inaccurate?  We often have treated AEO as definitive for purposes of projecting BAU energy demand.

**Comment by oashmoore** [comment] 2021-07-22 16:22
Ok we can sort this out using the AEO forecast! Thanks Jeff.

**Comment by robbieorvis** [comment] 2021-08-11 13:50
@jrissman true that at the national level in the US, the new AEO accounts for COVID. But for basically all the international models and also the state models (which do not necessarily use AEO2021 for forecasting because it only goes down to the census region level) there is not readily available detailed projection data including COVID impacts. In the EU we are using a dataset form from 2019, considered the gold standard, but it is pre COVID. In China we are using modeling from 2017 or 2019, also pre COVID. Same in Mexico. The US is actually the exception here: pretty much all regions lack data projections that account for COVID and are not on the annual data update cycle the EIA is on, so having the ability to explicitly model this in a detailed way in the EPS is actually still very valuable and likely will be for some time in all models other than the US model

We should discuss what the right level of subscripting is, i.e. the transportation example differs from electricity example in @oashmoore's opening comment, but having more flexibility either via fuel, tech, industry, etc... would definitely help us out.

**Comment by jrissman** [comment] 2021-08-12 09:49
Okay, I will add more subscripting to the input data powering this lever.  Right now, it is only subscripted by sector, which is indeed a blunt tool.  Given that it's going to still be needed in multiple regions, I agree that it can use refinement.

The important thing to keep in mind is that this lever represents a change in demand for goods and services due to a recession.  This of course will cause changes in fuel use.  But the lever doesn't **_directly_** cause or represent changes in fuel use - the changes in fuel use are a result of the change in demand for goods or services.

In the transportation sector, the relevant service is travel by mode, which means it should be subscripted by vehicle type and cargo type.  (For instance, Covid likely had a much different effect on demand for air travel vs. demand for travel by bus.)  I don't currently see any logical rationale for subscripting this by vehicle technology, because I don't see why the Covid recession would affect travel differently by vehicle technology.  For example, work-from-home requirements likely reduce the use of passenger LDVs (less commuting), but I don't see why work-from-home requirements would reduce the use of electric passenger LDVs more than gasoline engine passenger LDVs on a percentage basis.  (Maybe you have data showing EVs are disproportionately used for commuting and gasoline cars are disproportionately used for road trips, and commuting declined by more or less than road tripping, but this would be a pretty small and subtle effect, likely not worth trying to model.)

In the buildings sector, we actually already have different values for commercial buildings and for residential buildings, because we have different "Sector" subscripts for commercial vs. residential buildings.  If we subscript by Building Type, we get to split out rural residential vs. urban residential, which may in fact make sense, since I do think people responded to Covid differently in rural areas.  (Likely the impact was smaller than in urban areas.)  We could also potentially subscript by building component, though the rationale there is more iffy.  If you're home more often, you are using more lighting, more heating, and more cooking.  But I'm not sure whether your demand for lighting, heating, and cooking would increase by different percentages.  But I suppose people are at home more often during daylight hours, and restaurants are less appealing, so perhaps there are various sources of difference by building component.  I don't see any rationale for subscripting by building fuel, because if Covid increases demand for a building service (such as cooking), it would do so no matter what fuel people use for that purpose (i.e. whether people cook with electricity or with gas).  Everyone cooks more often using whatever appliances they already owned, so it shouldn't alter the balance of fuel use percentages for the same building service in the same building type (like cooking in urban residential buildings).

In the industry sector, it clearly ought to be subscripted by industry, since a recession affects demand for different goods differently.  Subscripting by fuel makes less sense, since industries already own their production lines with equipment that requires specific fuel types, and they can't easily or quickly change that in response to a short-term impact like a recession.  The typical lifetime of iron and steel or cement equipment is 40 years, for example.  Also, the lever affects process emissions, which do not have a fuel type.  (It also affects use of CCS, which corresponds to the activity of industries that are using CCS.)

In the electricity sector, it affects the net imports of electricity, which isn't subscripted at all.  It also affects the use of CCS by power plants, which is subscripted by plant type, but I don't think a recession would affect demand for CCS differently by plant type (or if so, it's such a small effect it's not worth modeling, unless doing a very deep dive into CCS uptake).   Electricity demand is controlled by the other sectors, which is why there is very little going on with this Covid recession lever in the electricity sector.

For fuel imports, exports, and production, it can be subscripted by fuel type.  This does not affect electricity - this is dealing with fuels like crude oil.  I think it makes sense to do this.

So the added subscripting that seems logical to me would be:

* Transport sector by vehicle type and cargo type
* Buildings sector by building type and maybe building component
* Industry sector by industry
* No change to electricity sector
* Fuel import/export/production by fuel type

I think this may take a little extra work to solve Olivia's problem because there isn't fuel-based subscripting that you can easily plug some percentage changes into.  You'd need to alter (say) demand for lighting in buildings to a different degree than demand for heating, and this would result in a different change to electricity use vs. natural gas use by those buildings.  I think that might be a good thing, because this helps explain **_why_** electricity use is higher or lower, instead of magically causing all electricity use in buildings to change at a different percentage from natural gas use.

What do you all think of this subscripting approach?

(Also, remember that you can always calibrate fuel use by fuel in the fuel demand variables like indst/BIFUbC, etc. by adding multipliers there to any combinations of subscripts you wish, if the calibration issue isn't specifically caused by inaccurate modeling of the Covid recession.)

**Comment by robbieorvis** [comment] 2021-08-12 13:10
Thanks, Jeff.

In general I agree with everything you’ve laid out.

The one area I want to look into is fuel use by industry sectors. In principle I agree with your summary but I’d like to see the data just confirm.

@Olivia ***@***.***> can you look at a few of the important industries in AEO2021 to see how fuel consumption within an industry changed due to COVID? If Jeff is right, we should find that fuel consumption moves up or down more or less proportionally to changes in value of shipments/outputs (which AEO also has).



________________________________
Robbie Orvis
Senior Director of Energy Policy Design
+1 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA 94111
www.energyinnovation.org<http://www.energyinnovation.org/>
***@***.***

**Comment by oashmoore** [comment] 2021-08-12 18:33
Thanks for that explanation. I think time series elasticities would be helpful because we're using different forecasts for different sectors. For buildings we're using NREL data, and for industrial fuel use we're using AEO. So we account for 2021 covid impacts in industry, but not buildings energy consumption in future years.

**Comment by jrissman** [comment] 2021-08-12 18:35
Okay, I will plan on making the values time-series.

**Comment by robbieorvis** [comment] 2024-04-12 20:39
I think we've moved past this and integrated whatever we needed to already. Closing.

**Closed by robbieorvis** 2024-04-12 20:39 UTC
Labels: low priority
